name: Modelops deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]
jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v4
      with:
          python-version: '3.8.12'

    - name: python version
      run: python --version
    - name: pip install
      run: pip install -r ia/deploy-ml/requirements.txt
    - name: download dataset
      run: wget -O ia/deploy-ml/data/stroke_data.csv ${{github.event.client_payload.dataseturl}}
    - name: cat dataset
      run: cat ia/deploy-ml/data/stroke_data.csv
      
    - name: Train model
      run: |
        cd model
        ls -la
        python train_stroke_model.py
     
    - name: docker build
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .
    - name: docker login
      run: docker images


    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha }}
